### ISSUE TITLE
ruff/isort configuration forces weird import block format

### ISSUE THREAD

**Issue by Omaraldarwish** [andrewyng/translation-agent#33]
* Clearly describe the bug: 
pyproject.toml configuration of iSort forces weird formatting of import block

```toml
[tool.ruff.lint.isort]
force-single-line = true
lines-after-imports = 2
known-first-party = ["translation-agent"]
```
* Instructions for reproducing the bug: 
trying to run pre-commit checks on a file that contains for example:

```python
from typing import ClassVar, Dict, Optional, Tuple
```

failes to pass check: I001 [*] Import block is un-sorted or un-formatted

when applying automatic fix, the import block looks like:

```python
from typing import ClassVar
from typing import Dict
from typing import Optional
from typing import Tuple
```

* Expected behavior: 
pre-commit checks should allow multiple imports from the same module using the same line!

* Proposed solution: 
change line 92 of pyproject.toml to force-single-line = false
